import random

Hangmanwords = [
    "programs",
    "default",
    "python",
    "inheritance",
    "method",
    "storage",
    "computer",
    "language",
    "computer",
    "machine",
    "attributes",
    "directory",
    "lowercase",
    "lists",
    "statement",
    "format",
    "syntax",
    "dictionary",
    "exception",
    "class",
    "instruction",
    "string",
    "integer",
    "debugging",
    "boolean",
    "tuples",
    "codes",
    "execution",
    "data",
    "function",
    "syntax",
    "character",
    "iteration",
    "programming",
    "database",
    "integer",
    "string",
    "float",
    "keyword",
    "recursion",
    "iterate",
    "software",
    "argument",
    "parameter",
    "variable",
    "input",
    "output",
    "compiler",
    "script",
    "method",
    "definition",
    "encrypt",
    "characters",
    "proccessor",
    "message",
    "Error",
    "print",
    "object",
    "execute",
    "iterator",
    "decrypt",
    "method",
    "uppercase",
    "interpreter",
    "loops",
    "iterable",
]


def getWord(wordLength):
    words = list(word for word in set(Hangmanwords) if len(word) == wordLength)
    return random.choice(words).upper()
